[versions]
koin = "4.0.4"

[libraries]
simularity = "info.debatty:java-string-similarity:2.0.0"
xlog = "com.elvishew:xlog:1.11.1"

ratingbar = "me.zhanghai.android.materialratingbar:library:1.4.0"
composeRatingbar = "com.github.a914-gowtham:compose-ratingbar:1.2.3"

versionsx = "com.github.ben-manes:gradle-versions-plugin:0.51.0"

sqlcipher = "net.zetetic:sqlcipher-android:4.9.0"

exifinterface = "androidx.exifinterface:exifinterface:1.3.7"

google-api-services-drive = "com.google.apis:google-api-services-drive:v3-rev197-1.25.0"
google-api-client-oauth = "com.google.oauth-client:google-oauth-client:1.39.0"

koin-core = { module = "io.insert-koin:koin-core", version.ref = "koin" }
koin-android = { module = "io.insert-koin:koin-android", version.ref = "koin" }

zxing-android-embedded = "com.journeyapps:zxing-android-embedded:4.3.0"
